# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/redhat
  block:

    - name: CIS | Ensure prelink is not installed
      become: true
      ansible.builtin.package:
        name: 'prelink'
        state: absent

    - name: CIS | Ensure apport is not installed
      become: true
      ansible.builtin.package:
        name: 'apport'
        state: absent

  # This block is only applicable to RedHat based systems
  when:
    - ansible_os_family == "Debian"

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_redhat'
